on:
  push:
    branches:
      - main
  pull_request:
  discussion:
    types: [opened, edited, deleted, answered, unanswered, locked, unlocked]
  discussion_comment:
    types: [created, edited, edited]

jobs:
  bridge_discussions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - uses: ./bridge 
        name: Run bridge
        with:
          discussions-category: test

      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 1 # Set to 0 for fetching all history for .GitInfo and .Lastmod

      # - name: Setup Hugo
      #   uses: peaceiris/actions-hugo@v2
      #   with:
      #     hugo-version: 'latest'
      #     extended: false

      # - name: Build and run tests
      #   run: hugo --minify
      #   working-directory: exampleSite
  
permissions:
  contents: read
  discussions: write

